services:
  whisperfusion:
    build:
      context: docker
      dockerfile: Dockerfile
    image: whisperfusion:latest
    volumes:
      - type: bind
        source: ./docker/scratch-space
        target: /root/scratch-space
    environment:
      VERBOSE: ${VERBOSE:-false}
      MODEL: ${MODEL:-Phi-3-mini-4k-instruct}
    ports:
      - "8888:8888"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    entrypoint: ["/root/scratch-space/run-whisperfusion.sh"]

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/resources/docker/default:/etc/nginx/conf.d/default.conf:ro
      - ./examples/chatbot/html:/var/www/html:ro
      - ./docker/scripts/start-nginx.sh:/start-nginx.sh:ro

    ports:
      - "8000:80"
    depends_on:
      - whisperfusion
    entrypoint: ["/bin/bash", "/start-nginx.sh"]
